typography_spectrum: 0.33269719826057553
content_rating:
  adult: false
color:
  brandStrength: 0.6120733851566911
  lightness: 0.4710327952634543
  saturation: 0.7231707077007741
  rhythmicContrast: 0.7006020571570843
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.7425021855160594
analytics:
  google: UA-80549435-1
author:
  name: Evrika Research Technologies
  email: inquiries@evrika.ca
logo: null
name: Evrika
title: Evrika Reserach Technologies
